name: Coverage Report

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-${{ github.event.workflow_run.id }}
          path: coverage

      - name: Download main Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-main
          path: coverage-main

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@5b6122e3a819a3be7b27fc961b7faafb3bf00e4d # v2.9.0
        with:
          file-coverage-mode: all
          json-summary-compare-path: coverage-main/coverage-summary.json
